---
name: Documentation Improvement
about: Suggest an improvement or correction to the documentation
labels: documentation
assignees: ''
---

**Describe the documentation issue**
A clear and concise description of what could be improved or corrected.

**Location of the documentation**
Please provide a link or file path to the documentation in question.

**Suggested change**
Describe what you would like to see changed or added.

**Additional context**
Add any other context or screenshots about the documentation issue here.
